spring:
  docker:
    compose:
      enabled: false

slack:
  signingSecret: ${SLACK_SIGNING_SECRET}
  botTokenA: ${SLACK_BOT_TOKEN_A}
  botTokenB: ${SLACK_BOT_TOKEN_B}
  broadcastChannel: ${BROADCAST_CHANNEL}
