spring:
# Temp turned off, we will use compose in the future but for now its just throwing errors.
  docker:
    compose:
      enabled: false

slack:
  signingSecret: ${SLACK_SIGNING_SECRET}
  botTokenA: ${SLACK_BOT_TOKEN_A}
  botTokenB: ${SLACK_BOT_TOKEN_B}
  broadcastChannel: ${BROADCAST_CHANNEL}
